import type { ScaffoldAnswers } from "../src/schema.js";
import type { IntegrationScenario } from "./types.js";

function common(): Omit<
  ScaffoldAnswers,
  | "projectName"
  | "patternId"
  | "memory"
  | "planning"
  | "prompts"
  | "knowledge"
  | "vectorBackend"
  | "tools"
  | "includeMcpServerSkeleton"
  | "useSqlDatabase"
  | "sqlBootstrap"
> {
  return {
    llm: {
      provider: "openai",
      model: "gpt-4o-mini",
      temperature: 0,
      maxTokens: 512,
      apiKeyEnvVar: "OPENAI_API_KEY",
    },
    mcpServers: [],
    databaseUrlEnvVar: "DATABASE_URL",
    sqliteFilePath: "data/integration.db",
    generateClaudeHandoff: false,
    tryClaudeSpawn: false,
  };
}

/** Full matrix of generated fixtures for local/CI integration. */
export const integrationScenarios: IntegrationScenario[] = [
  {
    id: "single-default",
    description: "Single agent, conversation memory, mock default",
    answers: {
      ...common(),
      projectName: "single-default",
      patternId: "single_agent",
      memory: "conversation",
      planning: "react_loop",
      prompts: "minimal",
      knowledge: "none",
      vectorBackend: "none",
      tools: [],
      useSqlDatabase: false,
      sqlBootstrap: "connection_url",
      includeMcpServerSkeleton: false,
    },
    mockScenario: "default",
    expectStdout: ["MOCK_OK"],
  },
  {
    id: "single-tools-http",
    description: "Single agent + http tool + tool mock",
    answers: {
      ...common(),
      projectName: "single-tools-http",
      patternId: "single_agent",
      memory: "none",
      planning: "react_loop",
      prompts: "minimal",
      knowledge: "none",
      vectorBackend: "none",
      tools: ["http"],
      useSqlDatabase: false,
      sqlBootstrap: "connection_url",
      includeMcpServerSkeleton: false,
    },
    mockScenario: "tool_roundtrip",
    expectStdout: ["MOCK_TOOL_DONE"],
  },
  {
    id: "single-production-prompt",
    description: "Production prompt pack still runs",
    answers: {
      ...common(),
      projectName: "single-production-prompt",
      patternId: "single_agent",
      memory: "none",
      planning: "none",
      prompts: "production",
      knowledge: "none",
      vectorBackend: "none",
      tools: [],
      useSqlDatabase: false,
      sqlBootstrap: "connection_url",
      includeMcpServerSkeleton: false,
    },
    mockScenario: "default",
    expectStdout: ["MOCK_OK"],
  },
  {
    id: "react-tool-loop",
    description: "ReAct topology + tool mock",
    answers: {
      ...common(),
      projectName: "react-tool-loop",
      patternId: "react",
      memory: "conversation",
      planning: "react_loop",
      prompts: "minimal",
      knowledge: "none",
      vectorBackend: "none",
      tools: ["http"],
      useSqlDatabase: false,
      sqlBootstrap: "connection_url",
      includeMcpServerSkeleton: false,
    },
    mockScenario: "tool_roundtrip",
    expectStdout: ["MOCK_TOOL_DONE"],
  },
  {
    id: "sequential-pipeline",
    description: "Sequential multi-agent topology",
    answers: {
      ...common(),
      projectName: "sequential-pipeline",
      patternId: "sequential",
      memory: "conversation",
      planning: "none",
      prompts: "minimal",
      knowledge: "none",
      vectorBackend: "none",
      tools: [],
      useSqlDatabase: false,
      sqlBootstrap: "connection_url",
      includeMcpServerSkeleton: false,
    },
    mockScenario: "default",
    expectStdout: ["MOCK_OK"],
  },
  {
    id: "parallel-batch",
    description: "Parallel topology",
    answers: {
      ...common(),
      projectName: "parallel-batch",
      patternId: "parallel",
      memory: "none",
      planning: "none",
      prompts: "minimal",
      knowledge: "none",
      vectorBackend: "none",
      tools: [],
      useSqlDatabase: false,
      sqlBootstrap: "connection_url",
      includeMcpServerSkeleton: false,
    },
    mockScenario: "default",
    expectStdout: ["MOCK_OK"],
  },
  {
    id: "coordinator-routing",
    description: "Coordinator topology",
    answers: {
      ...common(),
      projectName: "coordinator-routing",
      patternId: "coordinator",
      memory: "none",
      planning: "none",
      prompts: "minimal",
      knowledge: "none",
      vectorBackend: "none",
      tools: [],
      useSqlDatabase: false,
      sqlBootstrap: "connection_url",
      includeMcpServerSkeleton: false,
    },
    mockScenario: "default",
    expectStdout: ["MOCK_OK"],
  },
  {
    id: "hitl-skip",
    description: "Human-in-the-loop with SKIP_HITL",
    answers: {
      ...common(),
      projectName: "hitl-skip",
      patternId: "human_in_the_loop",
      memory: "none",
      planning: "none",
      prompts: "minimal",
      knowledge: "none",
      vectorBackend: "none",
      tools: [],
      useSqlDatabase: false,
      sqlBootstrap: "connection_url",
      includeMcpServerSkeleton: false,
    },
    mockScenario: "default",
    runEnv: { SKIP_HITL: "true" },
    expectStdout: ["MOCK_OK"],
  },
  {
    id: "custom-orchestrator",
    description: "Custom logic topology",
    answers: {
      ...common(),
      projectName: "custom-orchestrator",
      patternId: "custom_logic",
      memory: "none",
      planning: "none",
      prompts: "minimal",
      knowledge: "none",
      vectorBackend: "none",
      tools: [],
      useSqlDatabase: false,
      sqlBootstrap: "connection_url",
      includeMcpServerSkeleton: false,
    },
    mockScenario: "default",
    expectStdout: ["MOCK_OK"],
  },
  {
    id: "planner-executor",
    description: "Planner + executor stub",
    answers: {
      ...common(),
      projectName: "planner-executor",
      patternId: "single_agent",
      memory: "none",
      planning: "planner_executor_stub",
      prompts: "minimal",
      knowledge: "none",
      vectorBackend: "none",
      tools: ["http"],
      useSqlDatabase: false,
      sqlBootstrap: "connection_url",
      includeMcpServerSkeleton: false,
    },
    mockScenario: "planner_stub",
    expectStdout: ["MOCK_PLAN_EXECUTED"],
  },
  {
    id: "memory-file-persist",
    description: "File-backed memory",
    answers: {
      ...common(),
      projectName: "memory-file-persist",
      patternId: "single_agent",
      memory: "file",
      planning: "none",
      prompts: "minimal",
      knowledge: "none",
      vectorBackend: "none",
      tools: [],
      useSqlDatabase: false,
      sqlBootstrap: "connection_url",
      includeMcpServerSkeleton: false,
    },
    mockScenario: "default",
    runEnv: { MEMORY_FILE_PATH: "data/mem-it.json" },
    expectStdout: ["MOCK_OK"],
  },
  {
    id: "memory-db-sqlite",
    description: "DB-backed memory with SQLite",
    answers: {
      ...common(),
      projectName: "memory-db-sqlite",
      patternId: "single_agent",
      memory: "db",
      planning: "none",
      prompts: "minimal",
      knowledge: "none",
      vectorBackend: "none",
      tools: [],
      useSqlDatabase: true,
      sqlBootstrap: "sqlite_file",
      sqliteFilePath: "data/memory-agent.db",
      includeMcpServerSkeleton: false,
    },
    mockScenario: "default",
    expectStdout: ["MOCK_OK"],
    sqlSmoke: true,
  },
  {
    id: "memory-redis",
    description: "Redis memory (needs REDIS_URL from docker compose)",
    answers: {
      ...common(),
      projectName: "memory-redis",
      patternId: "single_agent",
      memory: "redis",
      planning: "none",
      prompts: "minimal",
      knowledge: "none",
      vectorBackend: "none",
      tools: [],
      useSqlDatabase: false,
      sqlBootstrap: "connection_url",
      includeMcpServerSkeleton: false,
    },
    mockScenario: "default",
    runEnv: { AGENT_SESSION_ID: "integration-redis-session" },
    expectStdout: ["MOCK_OK"],
    requiresRedis: true,
    assertRedisMemoryMinMessages: 2,
  },
  {
    id: "sql-sqlite-smoke",
    description: "SQLite Drizzle touch",
    answers: {
      ...common(),
      projectName: "sql-sqlite-smoke",
      patternId: "single_agent",
      memory: "conversation",
      planning: "none",
      prompts: "minimal",
      knowledge: "none",
      vectorBackend: "none",
      tools: [],
      useSqlDatabase: true,
      sqlBootstrap: "sqlite_file",
      sqliteFilePath: "data/sql-smoke.db",
      includeMcpServerSkeleton: false,
    },
    mockScenario: "default",
    expectStdout: ["MOCK_OK"],
    sqlSmoke: true,
  },
  {
    id: "knowledge-pgvector-postgres",
    description:
      "pgvector RAG + Postgres (needs DATABASE_URL, OPENAI_API_KEY — matches docker compose)",
    answers: {
      ...common(),
      projectName: "knowledge-pgvector-postgres",
      patternId: "single_agent",
      memory: "none",
      planning: "none",
      prompts: "minimal",
      knowledge: "vector_db",
      vectorBackend: "pgvector",
      tools: [],
      useSqlDatabase: true,
      sqlBootstrap: "connection_url",
      includeMcpServerSkeleton: false,
    },
    mockScenario: "default",
    expectStdout: ["MOCK_OK"],
    requiresPostgresPgvector: true,
    sqlSmoke: true,
  },
  {
    id: "knowledge-fs-stub",
    description: "Filesystem RAG stub in chain",
    answers: {
      ...common(),
      projectName: "knowledge-fs-stub",
      patternId: "single_agent",
      memory: "none",
      planning: "none",
      prompts: "minimal",
      knowledge: "filesystem_rag_stub",
      vectorBackend: "none",
      tools: [],
      useSqlDatabase: false,
      sqlBootstrap: "connection_url",
      includeMcpServerSkeleton: false,
    },
    mockScenario: "default",
    expectStdout: ["MOCK_OK"],
  },
  {
    id: "mcp-skeleton",
    description: "Includes MCP custom server skeleton",
    answers: {
      ...common(),
      projectName: "mcp-skeleton",
      patternId: "single_agent",
      memory: "none",
      planning: "none",
      prompts: "minimal",
      knowledge: "none",
      vectorBackend: "none",
      tools: [],
      useSqlDatabase: false,
      sqlBootstrap: "connection_url",
      includeMcpServerSkeleton: true,
    },
    mockScenario: "default",
    expectStdout: ["MOCK_OK"],
    assertMcpServerBuilt: true,
  },
];

export function quickScenarios(): IntegrationScenario[] {
  const pick = new Set([
    "single-default",
    "single-tools-http",
    "react-tool-loop",
    "sequential-pipeline",
    "sql-sqlite-smoke",
    "mcp-skeleton",
  ]);
  return integrationScenarios.filter((s) => pick.has(s.id));
}
